options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - europe-west1-docker.pkg.dev/relay-vm-498312/cloud-run-source-deploy/resuming-python:$COMMIT_SHA
      - -f
      - python-service/Dockerfile
      - python-service/

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - europe-west1-docker.pkg.dev/relay-vm-498312/cloud-run-source-deploy/resuming-python:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - resuming-python
      - --image=europe-west1-docker.pkg.dev/relay-vm-498312/cloud-run-source-deploy/resuming-python:$COMMIT_SHA
      - --region=europe-west1
      - --platform=managed
      - --allow-unauthenticated
      - --memory=2Gi
      - --cpu=2
      - --timeout=300
      - --concurrency=80
